<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>

<hr>

<a href="https://lms.clarusway.com/mod/lesson/view.php?id=2463&pageid=4531&startlastseen=no"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/2-DAwPY/DAwPy_S01_(Numpy_Arrays).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="90" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DAwPy_S1_%28Numpy_Arrays%29/DAwPy_S1_%28Numpy_Arrays%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="100" height="100" title="Open and Execute in nbviewer"></a><br/>

<hr>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="500" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="text-align: center;"><img src="https://i.ibb.co/XS0bxSH/best-bootcamps.png" width="300" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY_Courses"></p>

# <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Tasks for Session-1</p>

## Task 1 : Task: Random Matrix Generation and Operations:

### 1a. Generate a 4x4 matrix filled with random values.

In [2]:
import numpy as np

In [11]:
matrix1 = np.random.rand(16).reshape(4,4)
matrix1

array([[0.31551329, 0.60237987, 0.8482225 , 0.92918704],
       [0.93006519, 0.13668183, 0.93172346, 0.92748642],
       [0.75370083, 0.77400484, 0.59631941, 0.43225808],
       [0.6548541 , 0.07039324, 0.17261709, 0.40323911]])

In [24]:
matrix2 = np.random.randint(1, 8, 16)
matrix2 = matrix2.reshape(4,4)
matrix2

array([[6, 5, 2, 2],
       [7, 2, 5, 6],
       [7, 7, 4, 1],
       [5, 7, 2, 3]])

### 1b. Calculate the row sums of the matrix.

In [26]:
np.sum(matrix1, axis=1)

array([2.6953027 , 2.9259569 , 2.55628317, 1.30110354])

In [27]:
np.sum(matrix2, axis=1)

array([15, 20, 19, 17])

In [32]:
matrix2.sum(axis=1)

array([15, 20, 19, 17])

### 1c. Calculate the column means of the matrix.

In [34]:
np.mean(matrix1, axis=0)

array([0.66353335, 0.39586495, 0.63722062, 0.67304266])

In [35]:
np.mean(matrix2, axis=0)

array([6.25, 5.25, 3.25, 3.  ])

### 1d. Find the sum of the diagonal elements of the matrix.

In [40]:
matrix1.diagonal().sum()

1.4517536435822134

In [42]:
matrix2.diagonal().sum()

15

## Task 2: Array Sorting and Indexing:

### 2a. Create an array of random numbers from 1 to 20.

In [50]:
array1 = np.random.randint(1, 20, 20)
array1

array([14, 15, 13,  6,  7, 12,  7,  7,  9,  3, 13, 12, 10,  5, 17, 10, 15,
       18,  5,  8])

### 2b. Sort the array in descending order.

In [54]:
np.sort(array1)[::-1]

array([18, 17, 15, 15, 14, 13, 13, 12, 12, 10, 10,  9,  8,  7,  7,  7,  6,
        5,  5,  3])

### 2c. Find the minimum and maximum elements of the array.

In [57]:
max1 = np.max(array1)
min1 = np.min(array1)
max1, min1

(18, 3)

### 2d. Select the first half of the array (the first 10 elements) and reverse them.

In [60]:
array1[:10][::-1]

array([ 3,  9,  7,  7, 12,  7,  6, 13, 15, 14])

## Task 3: Convert the Arrays:

### 3a. Create an array with elements [-1, 0, 1, 2, 3].

In [61]:
array2 = np.array([-1, 0, 1, 2, 3])
array2

array([-1,  0,  1,  2,  3])

### 3b. Convert the array into a matrix and square each element.

In [66]:
new_array = array2.reshape(1,5)
new_array

array([[-1,  0,  1,  2,  3]])

In [67]:
new_array**2

array([[1, 0, 1, 4, 9]])

### 3c. Convert the matrix back to a one-dimensional array.

In [74]:
x = new_array.reshape(5)
x

array([-1,  0,  1,  2,  3])

### 3d. Convert each element of the array to its absolute value

In [73]:
np.absolute(x)

array([1, 0, 1, 2, 3])

<hr>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:150%; text-align:center; border-radius:10px 10px;">The End of Task</p>


<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>


<br><br><br>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="450" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>